import 'package:firebase_database/firebase_database.dart';

// Create a reference to the Firebase Realtime Database
final DatabaseReference usersReference =
    FirebaseDatabase.instance.ref().child('Users');

Future<void> createDynamicDetail(String username) async {
  // Get the current user count from the database
  DataSnapshot userCountSnapshot =
      (await usersReference.orderByKey().limitToLast(1).once()).snapshot;
  dynamic userCountData = userCountSnapshot.value;
  int userCount = 0;

  if (userCountData != null) {
    final lastUser = userCountData.values.first;
    userCount = lastUser['Number'] + 1;
  }

  // Generate an auto-generated user ID
  String autoGeneratedUserId = usersReference.push().key!;

  // Add the user with the auto-generated user ID and incrementing "Number"
  await usersReference.child(autoGeneratedUserId).set({
    'Username': username.toString(),
    'UserCount': userCount,
    'Status': 'Available',

    'Followers': {}, // Initialize an empty map for followers
    'Following': {}, // Initialize an empty map for following

    '_Posts': [],
    '_Stories': [],
    '_Replies': [],
    '_Comments': [],

    'Total_Views': 0,
    'Total_Likes': 0,

    'ProfileImg': 'null',
    'ProfileBannerImg': 'null',
  });
}
